version: '3.3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8333:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data_st:/var/lib/mysql

volumes:
  mysql_data_st:

